[package]
name = "async_cache"
version = "0.1.0"
authors = ["Pure White <wudi@purewhite.io>"]
edition = "2018"
description = "Async refresh cache."
repository = "https://github.com/PureWhiteWu/async_cache"
license = "MIT OR Apache-2.0"
keywords = ["cache", "async", "refresh"]
categories = ["asynchronous", "concurrency", "caching"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
